server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: url-shortener
  threads:
    virtual:
      enabled: true
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

logging:
  level:
    root: INFO
    com.urlshortener: DEBUG
