package com.urlshortener.service;

import com.urlshortener.common.exception.BusinessException;
import com.urlshortener.common.exception.ErrorCode;
import com.urlshortener.component.Base62Encoder;
import com.urlshortener.component.HashGenerator;
import com.urlshortener.component.SnowflakeIdGenerator;
import com.urlshortener.component.UrlValidator;
import com.urlshortener.dto.ShortenUrlRequest;
import com.urlshortener.dto.ShortenUrlResponse;
import com.urlshortener.entity.ShortUrl;
import com.urlshortener.repository.ShortUrlRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.Optional;

/**
 * 短網址核心業務服務 (引用 Spec §3.1 ~ §3.4, §6.3)
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class UrlShortenService {

    private static final int MAX_COLLISION_RETRIES = 3;

    private final ShortUrlRepository shortUrlRepository;
    private final UrlValidator urlValidator;
    private final HashGenerator hashGenerator;
    private final Base62Encoder base62Encoder;
    private final SnowflakeIdGenerator snowflakeIdGenerator;

    @Value("${app.short-url.domain:http://localhost:8080}")
    private String domainBaseUrl;

    /**
     * 建立短網址
     *
     * @param request 短網址生成請求 DTO
     * @return 短網址生成回應 DTO
     */
    @Transactional
    public ShortenUrlResponse createShortUrl(ShortenUrlRequest request) {
        // 1. 原始網址校驗與正規化
        String normalizedUrl = urlValidator.validateAndNormalizeUrl(request.getOriginalUrl());
        Instant now = Instant.now();
        Instant expiredAt = (request.getTtlInSeconds() != null) ? now.plusSeconds(request.getTtlInSeconds()) : null;
        long originalUrlHash = hashGenerator.hash64(normalizedUrl);

        String customAlias = request.getCustomAlias();

        // 2. 使用者自訂別名流程
        if (customAlias != null && !customAlias.isBlank()) {
            return processCustomAlias(customAlias.trim(), normalizedUrl, originalUrlHash, expiredAt, now);
        }

        // 3. 系統自動生成短碼流程 (含長網址查重冪等性)
        return processAutoGeneratedShortUrl(normalizedUrl, originalUrlHash, expiredAt, now);
    }

    private ShortenUrlResponse processCustomAlias(
            String customAlias,
            String normalizedUrl,
            long originalUrlHash,
            Instant expiredAt,
            Instant now
    ) {
        // 格式與保留字校驗
        urlValidator.validateCustomAlias(customAlias);

        // 唯一性檢查
        Optional<ShortUrl> existingOpt = shortUrlRepository.findByShortKey(customAlias);
        if (existingOpt.isPresent()) {
            ShortUrl existing = existingOpt.get();
            if (existing.isValid(now)) {
                throw new BusinessException(ErrorCode.CUSTOM_ALIAS_ALREADY_EXISTS, customAlias);
            }
            // 若既有短碼已過期，則可覆蓋更新
            existing.setOriginalUrl(normalizedUrl);
            existing.setOriginalUrlHash(originalUrlHash);
            existing.setIsCustom(true);
            existing.setStatus(ShortUrl.STATUS_ACTIVE);
            existing.setExpiredAt(expiredAt);
            ShortUrl saved = shortUrlRepository.save(existing);
            return toResponse(saved);
        }

        // 使用 Lombok 的 Builder 模式建立 Entity 實體物件
        // 【設計概念說明】：
        // 捨棄傳統 Java 先 new 出空物件再一行行呼叫 setXXX() 的繁瑣作法，
        // 改用 Builder 模式（鏈式呼叫 / Fluent API），具備以下優勢：
        // 1. 類似 Golang 指定欄位名稱的 Struct 賦值，大幅提升可讀性
        // 2. 避免長參數建構子容易傳錯順序的問題
        // 3. 欄位賦值完畢後透過 .build() 一次產出完整且不可隨意破壞狀態的實例
        ShortUrl newRecord = ShortUrl.builder()
                .shortKey(customAlias)
                .originalUrl(normalizedUrl)
                .originalUrlHash(originalUrlHash)
                .isCustom(true)
                .status(ShortUrl.STATUS_ACTIVE)
                .expiredAt(expiredAt)
                .build();

        ShortUrl saved = shortUrlRepository.save(newRecord);
        return toResponse(saved);
    }

    private ShortenUrlResponse processAutoGeneratedShortUrl(
            String normalizedUrl,
            long originalUrlHash,
            Instant expiredAt,
            Instant now
    ) {
        // 冪等性查重：若同長網址存在有效非自訂短網址，直接回傳
        Optional<ShortUrl> activeOpt = shortUrlRepository.findActiveByOriginalUrlHashAndOriginalUrl(
                originalUrlHash,
                normalizedUrl,
                now
        );
        if (activeOpt.isPresent()) {
            log.info("Reuse active short url for original url: {}", normalizedUrl);
            return toResponse(activeOpt.get());
        }

        // 生成候選短碼與防碰撞重試
        String shortKey = generateUniqueShortKey(normalizedUrl);

        ShortUrl newRecord = ShortUrl.builder()
                .shortKey(shortKey)
                .originalUrl(normalizedUrl)
                .originalUrlHash(originalUrlHash)
                .isCustom(false)
                .status(ShortUrl.STATUS_ACTIVE)
                .expiredAt(expiredAt)
                .build();

        ShortUrl saved = shortUrlRepository.save(newRecord);
        return toResponse(saved);
    }

    private String generateUniqueShortKey(String normalizedUrl) {
        // 第 0 次嘗試：MurmurHash3 32-bit 直接轉 Base62
        long rawHash = hashGenerator.hash32(normalizedUrl);
        String candidateKey = base62Encoder.encode(rawHash);

        if (!shortUrlRepository.existsByShortKey(candidateKey)) {
            return candidateKey;
        }

        log.warn("Hash collision detected on initial key: {}, retrying with salt...", candidateKey);

        // 第 1 ~ 3 次加鹽重試
        for (int retry = 1; retry <= MAX_COLLISION_RETRIES; retry++) {
            long saltedHash = hashGenerator.hashWithSalt(normalizedUrl, retry);
            String saltedCandidate = base62Encoder.encode(saltedHash);
            if (!shortUrlRepository.existsByShortKey(saltedCandidate)) {
                log.info("Collision resolved with salt retry count: {}", retry);
                return saltedCandidate;
            }
            log.warn("Hash collision retry {} failed for key: {}", retry, saltedCandidate);
        }

        // 3 次重試耗盡，觸發安全降級：雪花演算法 (Snowflake ID) -> Base62
        long snowflakeId = snowflakeIdGenerator.nextId();
        String fallbackKey = base62Encoder.encode(snowflakeId);
        log.warn("All collision retries exhausted. Activated Snowflake fallback key: {}", fallbackKey);
        return fallbackKey;
    }

    private ShortenUrlResponse toResponse(ShortUrl entity) {
        String base = domainBaseUrl.endsWith("/") ? domainBaseUrl.substring(0, domainBaseUrl.length() - 1) : domainBaseUrl;
        return ShortenUrlResponse.builder()
                .shortKey(entity.getShortKey())
                .shortUrl(base + "/" + entity.getShortKey())
                .originalUrl(entity.getOriginalUrl())
                .isCustom(entity.getIsCustom())
                .expiredAt(entity.getExpiredAt())
                .createdAt(entity.getCreatedAt())
                .build();
    }
}
